# .goreleaser.yml for tudomesh
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tudomesh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    binary: tudomesh

dockers_v2:
  - id: tudomesh
    images:
      - "kwv4/tudomesh"
    tags:
      - "{{ .Version }}"
      - "latest"
    dockerfile: Dockerfile
    labels:
      org.opencontainers.image.version: "{{ .Version }}"
    # Platforms to build for
    platforms:
      - linux/amd64
      - linux/arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
